import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Modal, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import * as ImageManipulator from 'expo-image-manipulator';
import { AdminButton, AdminCard, adminStyles as A, OwnerAdminShell } from '../components/owner-admin/OwnerAdminShell';
import { useTheme } from '../context/ThemeContext'; import { DarkColors, LightColors } from '../constants/colors'; import { supabase } from '../context/supabase'; import { useAuth } from '../context/AuthContext'; import { getCatalogImageUrl } from '../utils/imageUrl'; import { getOrderedCatalogIds } from '../utils/catalog';

type Product = { id:string; name:string; description:string|null; name_sq:string|null; name_en:string|null; description_sq:string|null; description_en:string|null; price:number; image_url:string|null; is_on_sale:boolean; sale_price:number|null; is_active:boolean; is_out_of_stock:boolean };
type Form = { nameSq:string; nameEn:string; descriptionSq:string; descriptionEn:string; price:string; salePrice:string; image:string; onSale:boolean; active:boolean };
const empty: Form = { nameSq:'', nameEn:'', descriptionSq:'', descriptionEn:'', price:'', salePrice:'', image:'', onSale:false, active:true };
const orderItems = (items: Product[], ids: string[]) => { const positions = new Map(ids.map((id,i)=>[id,i])); return [...items].sort((a,b)=>(positions.get(a.id)??999999)-(positions.get(b.id)??999999)); };

export default function OwnerProducts() {
  const { theme }=useTheme(); const C=theme==='dark'?DarkColors:LightColors; const { user }=useAuth();
  const [items,setItems]=useState<Product[]>([]); const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(false); const [translating,setTranslating]=useState(false); const [open,setOpen]=useState(false); const [edit,setEdit]=useState<Product|null>(null); const [form,setForm]=useState<Form>(empty);
  const load=useCallback(async()=>{ setLoading(true); const [{data,error},{data:orderData}]=await Promise.all([supabase.from('products').select('id,name,description,name_sq,name_en,description_sq,description_en,price,image_url,is_on_sale,sale_price,is_active,is_out_of_stock').order('created_at',{ascending:false}),supabase.from('content').select('value').eq('key','product_order').maybeSingle()]); if(error) Alert.alert('Gabim',error.message); setItems(orderItems(data??[],getOrderedCatalogIds(orderData?.value))); setLoading(false); },[]);
  useEffect(()=>{void load()},[load]);
  const filtered=useMemo(()=>items.filter(p=>{const q=search.trim().toLowerCase();return (!q||[p.name,p.name_sq,p.name_en].some(x=>x?.toLowerCase().includes(q)))&&(status==='all'||status==='active'&&p.is_active||status==='inactive'&&!p.is_active||status==='sold'&&p.is_out_of_stock)}),[items,search,status]);
  const show=(p?:Product)=>{setEdit(p??null);setForm(p?{nameSq:p.name_sq||p.name,nameEn:p.name_en||'',descriptionSq:p.description_sq||p.description||'',descriptionEn:p.description_en||'',price:String(p.price),salePrice:p.sale_price==null?'':String(p.sale_price),image:p.image_url||'',onSale:p.is_on_sale,active:p.is_active}:empty);setOpen(true)};
  const pick=async()=>{if(!user)return;const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Kërkohet leje','Lejoni qasjen te fotografitë.');return}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:1});if(result.canceled||!result.assets[0])return;setUploading(true);try{const optimized=await ImageManipulator.manipulateAsync(result.assets[0].uri,[{resize:{width:900,height:900}}],{compress:.72,format:ImageManipulator.SaveFormat.JPEG});const bytes=await fetch(optimized.uri).then(r=>r.arrayBuffer());const path=`${user.id}/${Date.now()}.jpg`;const {error}=await supabase.storage.from('products').upload(path,bytes,{contentType:'image/jpeg',cacheControl:'31536000'});if(error)throw error;setForm(x=>({...x,image:supabase.storage.from('products').getPublicUrl(path).data.publicUrl}))}catch(e:any){Alert.alert('Ngarkimi dështoi',e.message)}finally{setUploading(false)}};
  const translate=async()=>{if(!form.nameSq.trim()&&!form.descriptionSq.trim())return null;setTranslating(true);try{const one=async(text:string)=>{if(!text.trim())return'';const q=new URLSearchParams({client:'gtx',sl:'sq',tl:'en',dt:'t',q:text});const response=await fetch(`https://translate.googleapis.com/translate_a/single?${q}`);if(!response.ok)throw new Error('Shërbimi i përkthimit nuk është i disponueshëm.');const data=await response.json();return(data[0]??[]).map((part:any[])=>part[0]).join('')};const values=await Promise.all([one(form.nameSq),one(form.descriptionSq)]);setForm(x=>({...x,nameEn:values[0]||x.nameEn,descriptionEn:values[1]||x.descriptionEn}));return values}catch(e:any){Alert.alert('Përkthimi dështoi',e.message);return null}finally{setTranslating(false)}};
  const save=async()=>{const price=Number(form.price.replace(',','.')),sale=Number(form.salePrice.replace(',','.'));if(!form.nameSq.trim()||!Number.isFinite(price)||price<=0){Alert.alert('Kontrolloni të dhënat','Emri shqip dhe çmimi mbi zero janë të detyrueshëm.');return}if(form.onSale&&(!Number.isFinite(sale)||sale<=0||sale>=price)){Alert.alert('Zbritja nuk është valide','Çmimi me zbritje duhet të jetë më i ulët se çmimi normal.');return}setSaving(true);let nameEn=form.nameEn.trim(),descriptionEn=form.descriptionEn.trim();if(!nameEn||(form.descriptionSq.trim()&&!descriptionEn)){const translated=await translate();if(!translated){setSaving(false);return}nameEn=nameEn||translated[0];descriptionEn=descriptionEn||translated[1]}const payload={name:form.nameSq.trim(),description:form.descriptionSq.trim(),name_sq:form.nameSq.trim(),name_en:nameEn,description_sq:form.descriptionSq.trim(),description_en:descriptionEn,price,image_url:form.image||null,is_on_sale:form.onSale,sale_price:form.onSale?sale:null,is_active:form.active};const result=edit?await supabase.from('products').update(payload).eq('id',edit.id):await supabase.from('products').insert(payload);setSaving(false);if(result.error){Alert.alert('Ruajtja dështoi',result.error.message);return}setOpen(false);await load()};
  const move=async(p:Product,d:-1|1)=>{const i=items.findIndex(x=>x.id===p.id),j=i+d;if(i<0||j<0||j>=items.length)return;const next=[...items];[next[i],next[j]]=[next[j],next[i]];setItems(next);const{error}=await supabase.from('content').upsert({key:'product_order',value:{orderedIds:next.map(x=>x.id)}},{onConflict:'key'});if(error){Alert.alert('Renditja dështoi',error.message);await load()}};
  const remove=(p:Product)=>Alert.alert('Fshi produktin?',p.name,[{text:'Anulo',style:'cancel'},{text:'Fshi',style:'destructive',onPress:async()=>{const{error}=await supabase.from('products').delete().eq('id',p.id);if(error)Alert.alert('Gabim',error.message);else await load()}}]);
  return <OwnerAdminShell title="Produktet" subtitle="Katalogu i përbashkët i aplikacionit dhe website-it"><AdminButton label="+ Shto produkt" onPress={()=>show()}/><TextInput value={search} onChangeText={setSearch} placeholder="Kërko produkt" placeholderTextColor={C.muted} style={[A.input,{color:C.text,borderColor:C.border,backgroundColor:C.card,marginVertical:13}]}/><View style={[A.chips,{marginBottom:13}]}>{[['all','Të gjitha'],['active','Aktive'],['inactive','Joaktive'],['sold','Nuk ka në stok']].map(([key,label])=><Pressable key={key} onPress={()=>setStatus(key)} style={[A.chip,{borderColor:C.border,backgroundColor:status===key?C.primary:C.card}]}><Text style={{color:status===key?C.onPrimary:C.text}}>{label}</Text></Pressable>)}</View>
    {loading?<ActivityIndicator color={C.primary}/>:filtered.map((p,i)=><AdminCard key={p.id}><View style={A.row}><Image source={{uri:getCatalogImageUrl(p.image_url)??undefined}} style={styles.image}/><View style={{flex:1}}><Text style={[A.name,{color:C.text}]}>{p.name_sq||p.name}</Text><Text style={[A.muted,{color:C.muted}]}>EN: {p.name_en||'mungon'} · {(p.is_on_sale&&p.sale_price?p.sale_price:p.price).toFixed(2)} €</Text><Text style={{color:p.is_out_of_stock?C.danger:p.is_active?C.success:C.muted}}>{p.is_out_of_stock?'Nuk ka në stok':p.is_active?'Aktiv':'Joaktiv'}</Text></View></View><View style={A.actions}><AdminButton label="↑" secondary disabled={i===0} onPress={()=>void move(p,-1)}/><AdminButton label="↓" secondary disabled={i===items.length-1} onPress={()=>void move(p,1)}/><AdminButton label="Ndrysho" secondary onPress={()=>show(p)}/><AdminButton label="Fshi" danger onPress={()=>remove(p)}/></View></AdminCard>)}
    <Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={styles.overlay}><View style={[styles.modal,{backgroundColor:C.card}]}><ScrollView keyboardShouldPersistTaps="handled"><Text style={[styles.title,{color:C.text}]}>{edit?'Ndrysho produktin':'Produkt i ri'}</Text><Text style={[A.muted,{color:C.muted}]}>Shkruaj shqip; versioni anglisht gjenerohet dhe mbetet i editueshëm.</Text><Field label="Emri (shqip)" value={form.nameSq} set={v=>setForm(x=>({...x,nameSq:v}))} C={C}/><View style={A.actions}><AdminButton label={translating?'Duke përkthyer…':'Gjenero anglisht'} disabled={translating} secondary onPress={()=>void translate()}/></View><Field label="Emri (anglisht)" value={form.nameEn} set={v=>setForm(x=>({...x,nameEn:v}))} C={C}/><Field label="Përshkrimi (shqip)" value={form.descriptionSq} set={v=>setForm(x=>({...x,descriptionSq:v}))} C={C} multi/><Field label="Përshkrimi (anglisht)" value={form.descriptionEn} set={v=>setForm(x=>({...x,descriptionEn:v}))} C={C} multi/><Field label="Çmimi" value={form.price} set={v=>setForm(x=>({...x,price:v}))} C={C} keyboard/><View style={A.actions}><AdminButton label={uploading?'Duke ngarkuar…':'Zgjidh fotografinë'} disabled={uploading} secondary onPress={()=>void pick()}/></View>{form.image?<Image source={{uri:form.image}} style={styles.preview}/>:null}<Toggle label="Me zbritje" value={form.onSale} set={v=>setForm(x=>({...x,onSale:v}))} C={C}/>{form.onSale&&<Field label="Çmimi me zbritje" value={form.salePrice} set={v=>setForm(x=>({...x,salePrice:v}))} C={C} keyboard/>}<Toggle label="Publikuar" value={form.active} set={v=>setForm(x=>({...x,active:v}))} C={C}/><View style={A.actions}><AdminButton label="Anulo" secondary onPress={()=>setOpen(false)}/><AdminButton label={saving?'Duke ruajtur…':'Ruaj'} disabled={saving||uploading||translating} onPress={()=>void save()}/></View></ScrollView></View></View></Modal>
  </OwnerAdminShell>;
}
function Field({label,value,set,C,multi,keyboard}:{label:string;value:string;set:(v:string)=>void;C:typeof LightColors;multi?:boolean;keyboard?:boolean}){return <View style={{marginTop:12}}><Text style={[A.label,{color:C.text}]}>{label}</Text><TextInput value={value} onChangeText={set} multiline={multi} keyboardType={keyboard?'decimal-pad':'default'} style={[A.input,multi&&{minHeight:88,textAlignVertical:'top',paddingTop:12},{color:C.text,borderColor:C.border,backgroundColor:C.surface}]}/></View>}
function Toggle({label,value,set,C}:{label:string;value:boolean;set:(v:boolean)=>void;C:typeof LightColors}){return <View style={[A.between,{marginTop:15}]}><Text style={{color:C.text,fontWeight:'700'}}>{label}</Text><Switch value={value} onValueChange={set}/></View>}
const styles=StyleSheet.create({image:{width:68,height:68,borderRadius:14,backgroundColor:'#ddd'},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'flex-end'},modal:{maxHeight:'94%',padding:20,paddingBottom:38,borderTopLeftRadius:24,borderTopRightRadius:24},title:{fontSize:21,fontWeight:'900'},preview:{width:110,height:110,borderRadius:15,marginTop:12}});
