import { useCallback,useEffect,useMemo,useState } from 'react'; import { ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View } from 'react-native'; import { AdminButton,AdminCard,adminStyles as A,OwnerAdminShell } from '../components/owner-admin/OwnerAdminShell'; import { useTheme } from '../context/ThemeContext'; import { DarkColors,LightColors } from '../constants/colors'; import { supabase } from '../context/supabase';
type Item={name:string;quantity:number;price:number}; type Order={id:string;display_order_id:string|null;created_at:string;status:string;total:number;subtotal:number;discount:number;promo_code:string|null;full_name:string;phone:string;address:string;items:Item[]}; const statuses=['ordered','confirmed','delivered','cancelled']; const labels:Record<string,string>={ordered:'Porositur',confirmed:'Konfirmuar',delivered:'Dorëzuar',cancelled:'Anuluar'};
export default function OwnerOrders(){const{theme}=useTheme();const C=theme==='dark'?DarkColors:LightColors;const[items,setItems]=useState<Order[]>([]),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.from('orders').select('id,display_order_id,created_at,status,total,subtotal,discount,promo_code,full_name,phone,address,items').order('created_at',{ascending:false});if(error)Alert.alert('Gabim',error.message);setItems(data??[]);setLoading(false)},[]);useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>items.filter(o=>{const q=search.trim().toLowerCase();return(!q||[o.full_name,o.phone,o.address,o.display_order_id,o.id].some(v=>v?.toLowerCase().includes(q)))&&(status==='all'||o.status===status)}),[items,search,status]);const revenue=filtered.filter(o=>o.status!=='cancelled').reduce((n,o)=>n+Number(o.total||0),0);
 const update=async(o:Order,next:string)=>{setBusy(o.id);const{data,error}=await supabase.rpc('owner_manage_order',{p_order_id:o.id,p_action:'set_status',p_status:next});setBusy('');if(error){Alert.alert('Përditësimi dështoi',error.message);return}setItems(v=>v.map(x=>x.id===o.id?{...x,status:next}:x));const awarded=Number(data?.points_awarded||0);if(next==='delivered')Alert.alert('Porosia u dorëzua',awarded>0?`${awarded} Fresh Points iu shtuan klientit.`:'Porosia u mbyll. Nuk kishte llogari klienti për Fresh Points.');};
 const remove=(o:Order)=>Alert.alert('Fshi porosinë?','Anulimi është zakonisht më i sigurt. Fshirja largon historikun.',[{text:'Anulo',style:'cancel'},{text:'Fshi',style:'destructive',onPress:async()=>{setBusy(o.id);const{error}=await supabase.rpc('owner_manage_order',{p_order_id:o.id,p_action:'delete',p_status:null});setBusy('');if(error)Alert.alert('Fshirja dështoi',error.message);else setItems(v=>v.filter(x=>x.id!==o.id))}}]);
 return <OwnerAdminShell title="Porositë" subtitle="Kërko dhe përcill porositë online"><View style={styles.summary}><AdminCard><Text style={[styles.big,{color:C.text}]}>{filtered.length}</Text><Text style={{color:C.muted}}>Porosi</Text></AdminCard><AdminCard><Text style={[styles.big,{color:C.text}]}>{revenue.toFixed(2)} €</Text><Text style={{color:C.muted}}>Të ardhura</Text></AdminCard></View><TextInput value={search} onChangeText={setSearch} placeholder="Emër, telefon, adresë ose ID" placeholderTextColor={C.muted} style={[A.input,{color:C.text,borderColor:C.border,backgroundColor:C.card,marginBottom:12}]}/><View style={[A.chips,{marginBottom:13}]}>{['all',...statuses].map(s=><Pressable key={s} onPress={()=>setStatus(s)} style={[A.chip,{borderColor:C.border,backgroundColor:status===s?C.primary:C.card}]}><Text style={{color:status===s?C.onPrimary:C.text}}>{s==='all'?'Të gjitha':labels[s]}</Text></Pressable>)}</View>
 {loading?<ActivityIndicator color={C.primary}/>:filtered.map(o=><AdminCard key={o.id}><View style={A.between}><View style={{flex:1}}><Text style={[A.name,{color:C.text}]}>Porosia {o.display_order_id||o.id.slice(0,6)}</Text><Text style={[A.muted,{color:C.muted}]}>{new Date(o.created_at).toLocaleString('sq-AL')} · {o.full_name}</Text><Text style={[A.muted,{color:C.muted}]}>{o.phone} · {o.address}</Text></View><Text style={[styles.total,{color:C.primary}]}>{Number(o.total).toFixed(2)} €</Text></View><View style={styles.lines}>{o.items?.map((x,i)=><View key={i} style={A.between}><Text style={{color:C.text}}>{x.name} × {x.quantity}</Text><Text style={{color:C.muted}}>{(x.price*x.quantity).toFixed(2)} €</Text></View>)}</View><Text style={[A.label,{color:C.text,marginTop:12}]}>Statusi: {labels[o.status]||o.status}</Text>{!['delivered','cancelled'].includes(o.status)&&<View style={A.chips}>{(o.status==='ordered'?['confirmed','delivered','cancelled']:['delivered','cancelled']).map(s=><Pressable disabled={busy===o.id} key={s} onPress={()=>void update(o,s)} style={[A.chip,{borderColor:C.border,backgroundColor:C.surface,opacity:busy===o.id?.5:1}]}><Text style={{color:C.text}}>{labels[s]}</Text></Pressable>)}</View>}<View style={A.actions}>{o.status!=='delivered'&&<AdminButton label="Fshi" danger disabled={busy===o.id} onPress={()=>remove(o)}/>}</View></AdminCard>)}
 </OwnerAdminShell>}
const styles=StyleSheet.create({summary:{flexDirection:'row',gap:10},big:{fontSize:20,fontWeight:'900'},total:{fontWeight:'900',fontSize:16},lines:{marginTop:13,gap:7}});
