import { useCallback,useEffect,useState } from 'react'; import { ActivityIndicator,Alert,Modal,Pressable,StyleSheet,Switch,Text,TextInput,View } from 'react-native';
import { AdminButton,AdminCard,adminStyles as A,OwnerAdminShell } from '../components/owner-admin/OwnerAdminShell'; import { useTheme } from '../context/ThemeContext'; import { DarkColors,LightColors } from '../constants/colors'; import { supabase } from '../context/supabase';
type Promo={id:string;code:string;discount_type:'percentage'|'fixed';discount_value:number;expires_at:string|null;is_active:boolean}; type Form={code:string;type:'percentage'|'fixed';value:string;expires:string;active:boolean}; const empty:Form={code:'',type:'percentage',value:'',expires:'',active:true};
export default function OwnerPromos(){const{theme}=useTheme();const C=theme==='dark'?DarkColors:LightColors;const[items,setItems]=useState<Promo[]>([]),[form,setForm]=useState<Form>(empty),[edit,setEdit]=useState<Promo|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);const{data,error}=await supabase.from('promo_codes').select('id,code,discount_type,discount_value,expires_at,is_active').order('created_at',{ascending:false});if(error)Alert.alert('Gabim',error.message);setItems(data??[]);setLoading(false)},[]);useEffect(()=>{void load()},[load]);
 const show=(p?:Promo)=>{setEdit(p??null);setForm(p?{code:p.code,type:p.discount_type,value:String(p.discount_value),expires:p.expires_at?.slice(0,10)??'',active:p.is_active}:empty);setOpen(true)};
 const save=async()=>{const n=Number(form.value.replace(',','.'));if(!form.code.trim()||!Number.isFinite(n)||n<=0||(form.type==='percentage'&&n>100)){Alert.alert('Kontrolloni të dhënat','Kodi kërkohet; zbritja duhet të jetë mbi 0 dhe përqindja jo më shumë se 100.');return}setSaving(true);const payload={code:form.code.trim().toUpperCase(),discount_type:form.type,discount_value:n,expires_at:form.expires?new Date(form.expires+'T23:59:59').toISOString():null,is_active:form.active};const r=edit?await supabase.from('promo_codes').update(payload).eq('id',edit.id):await supabase.from('promo_codes').insert(payload);setSaving(false);if(r.error){Alert.alert('Ruajtja dështoi',r.error.message);return}setOpen(false);await load()};
 const remove=(p:Promo)=>Alert.alert('Fshi kodin?',p.code,[{text:'Anulo',style:'cancel'},{text:'Fshi',style:'destructive',onPress:async()=>{const{error}=await supabase.from('promo_codes').delete().eq('id',p.id);if(error)Alert.alert('Gabim',error.message);else await load()}}]);
 return <OwnerAdminShell title="Kodet promo" subtitle="Zbritje për porositë online"><AdminButton label="+ Shto kod promo" onPress={()=>show()}/><View style={{height:14}}/>{loading?<ActivityIndicator color={C.primary}/>:items.map(p=><AdminCard key={p.id}><View style={A.between}><View><Text style={[A.name,{color:C.text}]}>{p.code}</Text><Text style={[A.muted,{color:C.muted}]}>{p.discount_type==='percentage'?`${p.discount_value}%`:`${p.discount_value.toFixed(2)} €`} · {p.expires_at?`skadon ${p.expires_at.slice(0,10)}`:'pa skadim'} · {p.is_active?'aktiv':'joaktiv'}</Text></View></View><View style={A.actions}><AdminButton label="Ndrysho" secondary onPress={()=>show(p)}/><AdminButton label="Fshi" danger onPress={()=>remove(p)}/></View></AdminCard>)}
 <Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={styles.overlay}><View style={[styles.modal,{backgroundColor:C.card}]}><Text style={[styles.title,{color:C.text}]}>{edit?'Ndrysho kodin':'Kod i ri promo'}</Text><Field label="Kodi" value={form.code} set={v=>setForm(x=>({...x,code:v.toUpperCase()}))} C={C}/><Text style={[A.label,{color:C.text}]}>Lloji</Text><View style={A.chips}>{(['percentage','fixed'] as const).map(t=><Pressable key={t} onPress={()=>setForm(x=>({...x,type:t}))} style={[A.chip,{borderColor:C.border,backgroundColor:form.type===t?C.primary:C.surface}]}><Text style={{color:form.type===t?C.onPrimary:C.text}}>{t==='percentage'?'Përqindje':'Vlerë fikse'}</Text></Pressable>)}</View><Field label="Vlera" value={form.value} set={v=>setForm(x=>({...x,value:v}))} C={C} keyboard/><Field label="Skadimi (YYYY-MM-DD, opsional)" value={form.expires} set={v=>setForm(x=>({...x,expires:v}))} C={C}/><View style={[A.between,{marginVertical:12}]}><Text style={{color:C.text,fontWeight:'700'}}>Aktiv</Text><Switch value={form.active} onValueChange={v=>setForm(x=>({...x,active:v}))}/></View><View style={A.actions}><AdminButton label="Anulo" secondary onPress={()=>setOpen(false)}/><AdminButton label={saving?'Duke ruajtur…':'Ruaj'} disabled={saving} onPress={()=>void save()}/></View></View></View></Modal>
 </OwnerAdminShell>}
function Field({label,value,set,C,keyboard}:{label:string;value:string;set:(v:string)=>void;C:typeof LightColors;keyboard?:boolean}){return <View style={{marginTop:13}}><Text style={[A.label,{color:C.text}]}>{label}</Text><TextInput value={value} onChangeText={set} keyboardType={keyboard?'decimal-pad':'default'} style={[A.input,{color:C.text,borderColor:C.border,backgroundColor:C.surface}]}/></View>}
const styles=StyleSheet.create({overlay:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'flex-end'},modal:{padding:20,paddingBottom:38,borderTopLeftRadius:24,borderTopRightRadius:24},title:{fontSize:21,fontWeight:'900',marginBottom:4}});
